# Generated by Django 4.1.3 on 2022-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_randuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
