# Generated by Django 4.1.3 on 2022-11-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_randuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='randuser',
            name='birthday_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
