# Generated by Django 4.1.3 on 2022-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_randuser_birthday_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='randuser',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='randuser',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='randuser',
            name='user_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='randuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
