# Generated by Django 4.1.3 on 2022-12-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_randuser_first_name_randuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randuser',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
