# Generated by Django 4.1.3 on 2022-11-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_randuser_first_name_randuser_last_name_and_more'),
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creat_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.randuser'),
        ),
    ]
