# Generated by Django 4.1.3 on 2022-12-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_creat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='from_project',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.project'),
        ),
    ]
